- name: Import Common NodeJS
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Import prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter